# .eslintrc.yaml

# Aturan-aturan ESLint
rules:
  # Contoh aturan: semi harus diakhiri dengan tanda koma
  semi: [2, "always"]

# Pilihan untuk ESLint
env:
  # Lingkungan untuk Node.js
  node: true

# Ekstensi yang akan digunakan
extends:
  # Aturan-aturan bawaan ESLint untuk React
  - "eslint:recommended"
  - "plugin:react/recommended"

# Pengaturan spesifik plugin
plugins:
  # Plugin untuk React
  - react

# Konfigurasi untuk parser dan parserOptions
parser: "@typescript-eslint/parser"
parserOptions:
  # Bekerja dengan modul ES6
  sourceType: "module"
  # Mendukung fitur-fitur TypeScript
  ecmaFeatures:
    jsx: true
  # Menyesuaikan dengan tsconfig
  project: "./tsconfig.json"
  tsconfigRootDir: __dirname

# Pengaturan tambahan untuk TypeScript
overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - "plugin:@typescript-eslint/recommended"
      - "plugin:@typescript-eslint/recommended-requiring-type-checking"
    parserOptions:
      # Aktifkan type-checking
      project: "./tsconfig.json"
